communityconfig_search:
  url: /communityconfig/search.json
  param: { module: communityconfig, action: search, sf_format: json }
  requirements: { sf_method: [get] }
communityconfig_update:
  url: /communityconfig/update.json
  param: { module: communityconfig, action: update, sf_format: json }
  requirements: { sf_method: [get] }
memberconfig_search:
  url: /memberconfig/search.json
  param: { module: memberconfig, action: search, sf_format: json }
  requirements: { sf_method: [get] }
memberconfig_update:
  url: /memberconfig/update.json
  param: { module: memberconfig, action: update, sf_format: json }
  requirements: { sf_method: [get] }
snsconfig_search:
  url: /snsconfig/search.json
  param: { module: snsconfig, action: search, sf_format: json }
  requirements: { sf_method: [get] }
snsconfig_update:
  url: /snsconfig/update.json
  param: { module: snsconfig, action: update, sf_format: json }
  requirements: { sf_method: [get] }

